FROM alpine:latest

LABEL "com.github.actions.name"="hello world"
LABEL "com.github.actions.description"="Displays a Hello World Message"
LABEL "com.github.actions.icon"="activity"
LABEL "com.github.actions.color"="yellow"

RUN apk add --no-cache \
    bash 


CMD ["echo", "hello world"]